version: '3'
services:
  nginx:
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: stage
    environment:
      - NODE_ENV=stage
      - MONGO_USER=franco
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=keyboard_cat
    command: node index.js

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=franco
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
