version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=franco
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=keyboard_cat
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=franco
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

